import 'package:decimal/decimal.dart';
import 'package:dividendendackel/domain/analytics/dividend_growth.dart';
import 'package:dividendendackel/domain/entities/entities.dart';

/// Whether a deterministic dividend forecast could be produced.
enum DividendForecastStatus {
  /// Regular history supplied an explainable schedule.
  available,

  /// No reported dividend history exists.
  noReportedHistory,

  /// The observed schedule is explicitly or empirically irregular.
  irregularSchedule,

  /// Amount history exists, but no recurring ex- or payment-date pattern does.
  missingSeasonality,
}

/// Source of the annual growth assumption.
enum ForecastGrowthBasis { dividendCagr, defaultRate }

/// Growth rate and plain-language reason used by a forecast.
final class ForecastGrowthAssumption {
  /// Creates a growth assumption.
  const ForecastGrowthAssumption({
    required this.rate,
    required this.basis,
    required this.explanation,
    this.cagrPeriodYears,
  });

  /// Annual growth applied to generated payments.
  final Percentage rate;

  /// Whether history or the documented fallback supplied [rate].
  final ForecastGrowthBasis basis;

  /// Human-readable basis shown alongside estimated values.
  final String explanation;

  /// CAGR period used when [basis] is [ForecastGrowthBasis.dividendCagr].
  final int? cagrPeriodYears;
}

/// Explainable result of the rule-based forecast engine.
final class DividendForecast {
  /// Creates a forecast result.
  const DividendForecast({
    required this.instrumentId,
    required this.currency,
    required this.status,
    required this.frequency,
    required this.events,
    required this.asOf,
    required this.horizonEnd,
    required this.explanation,
    this.growthAssumption,
    this.confidence,
  });

  /// Forecasted instrument.
  final String instrumentId;

  /// Currency shared by all event values.
  final Currency currency;

  /// Availability and limitation marker.
  final DividendForecastStatus status;

  /// Detected payment schedule.
  final DividendFrequency frequency;

  /// Known future events plus generated estimates, ordered by calendar date.
  final List<DividendEvent> events;

  /// Calendar day from which the forecast was made.
  final DateTime asOf;

  /// Exclusive forecast boundary.
  final DateTime horizonEnd;

  /// Plain-language explanation of the result or limitation.
  final String explanation;

  /// Growth basis, when a forecast was possible.
  final ForecastGrowthAssumption? growthAssumption;

  /// Confidence in generated estimates. Reported events retain their own
  /// provenance confidence.
  final Confidence? confidence;

  /// Only events generated by the rule-based engine.
  List<DividendEvent> get estimatedEvents => events
      .where(
        (DividendEvent event) =>
            event.status == DividendStatus.historicallyEstimated,
      )
      .toList(growable: false);

  /// Provider-reported events retained unchanged in the forecast horizon.
  List<DividendEvent> get reportedEvents => events
      .where((DividendEvent event) => event.status.isConfirmedByCompany)
      .toList(growable: false);
}

/// Deterministic, explainable dividend forecast engine (Vision.md §11).
final class DividendForecastEngine {
  /// Creates an engine.
  DividendForecastEngine({
    Percentage? fallbackGrowthRate,
    this.defaultHorizonMonths = 24,
    this.growthCalculator = const DividendGrowthCalculator(),
  }) : fallbackGrowthRate = fallbackGrowthRate ?? Percentage.parsePercent('3') {
    if (this.fallbackGrowthRate.rate <= -Decimal.one) {
      throw ArgumentError.value(
        fallbackGrowthRate,
        'fallbackGrowthRate',
        'must be greater than -100%',
      );
    }
    if (defaultHorizonMonths <= 0) {
      throw ArgumentError.value(
        defaultHorizonMonths,
        'defaultHorizonMonths',
        'must be positive',
      );
    }
  }

  /// Explicit documented fallback used when three-year CAGR is unavailable.
  final Percentage fallbackGrowthRate;

  /// Default horizon; aligned with the 24-month forecast required by D5.
  final int defaultHorizonMonths;

  /// Historical growth calculator.
  final DividendGrowthCalculator growthCalculator;

  /// Forecast provenance source identifier.
  static const String forecastSource = 'forecast';

  /// Produces known and estimated future dividend events.
  DividendForecast forecast({
    required String instrumentId,
    required Currency currency,
    required List<DividendEvent> events,
    required DateTime asOf,
    int? horizonMonths,
  }) {
    if (instrumentId.trim().isEmpty) {
      throw ArgumentError.value(
        instrumentId,
        'instrumentId',
        'must not be empty',
      );
    }
    final int months = horizonMonths ?? defaultHorizonMonths;
    if (months <= 0) {
      throw ArgumentError.value(months, 'horizonMonths', 'must be positive');
    }
    final DateTime start = _calendarDay(asOf);
    final DateTime end = _addMonths(start, months);
    final List<DividendEvent> target = events
        .where((DividendEvent event) => event.instrumentId == instrumentId)
        .toList(growable: false);
    for (final DividendEvent event in target) {
      if (event.amountPerShare.currency != currency) {
        throw ArgumentError(
          'Dividend currency ${event.amountPerShare.currency.code} does not '
          'match ${currency.code} for $instrumentId.',
        );
      }
      if (event.amountPerShare.isNegative) {
        throw ArgumentError('Dividend amounts cannot be negative.');
      }
    }

    final List<DividendEvent> reported = target
        .where((DividendEvent event) => event.status.isConfirmedByCompany)
        .toList(growable: false);
    final List<DividendEvent> knownFuture = reported
        .where((DividendEvent event) {
          final Iterable<DateTime> dates = <DateTime?>[
            event.exDate,
            event.paymentDate,
          ].whereType<DateTime>().map(_calendarDay);
          return dates.any(
            (DateTime date) => !date.isBefore(start) && date.isBefore(end),
          );
        })
        .toList(growable: false);

    if (reported.isEmpty) {
      return _unavailable(
        instrumentId: instrumentId,
        currency: currency,
        status: DividendForecastStatus.noReportedHistory,
        frequency: DividendFrequency.unknown,
        knownFuture: knownFuture,
        start: start,
        end: end,
        explanation:
            'No reported dividend history is available, so no estimate was '
            'created.',
      );
    }

    final DividendFrequency frequency = _inferFrequency(reported, start.year);
    final int? expectedPayments = frequency.paymentsPerYear;
    if (expectedPayments == null) {
      return _unavailable(
        instrumentId: instrumentId,
        currency: currency,
        status: DividendForecastStatus.irregularSchedule,
        frequency: frequency,
        knownFuture: knownFuture,
        start: start,
        end: end,
        explanation:
            'The reported payments do not form a regular schedule. Known '
            'events are shown, but the app did not invent future dates.',
      );
    }

    final _SeasonalSchedule? schedule = _findSchedule(
      reported,
      beforeYear: start.year,
      expectedPayments: expectedPayments,
    );
    if (schedule == null) {
      return _unavailable(
        instrumentId: instrumentId,
        currency: currency,
        status: DividendForecastStatus.missingSeasonality,
        frequency: frequency,
        knownFuture: knownFuture,
        start: start,
        end: end,
        explanation:
            'Dividend amounts exist, but there are not enough dated payments '
            'to infer a recurring calendar pattern.',
      );
    }

    final DividendGrowthAnalysis growth = growthCalculator.calculate(
      instrumentId: instrumentId,
      currency: currency,
      events: target,
      asOf: start,
    );
    final DividendCagr? selectedCagr = _longestCagr(growth.cagrs);
    final int completeScheduleYears = _completeScheduleYears(
      reported,
      schedule,
      beforeYear: start.year,
    );
    final ForecastGrowthAssumption growthAssumption;
    final Confidence confidence;
    if (selectedCagr != null) {
      growthAssumption = ForecastGrowthAssumption(
        rate: selectedCagr.rate,
        basis: ForecastGrowthBasis.dividendCagr,
        cagrPeriodYears: selectedCagr.periodYears,
        explanation:
            'Estimated from the instrument’s '
            '${selectedCagr.periodYears}-year dividend CAGR '
            '(${selectedCagr.rate.format(withSign: true)} p.a.).',
      );
      confidence = completeScheduleYears >= 3
          ? Confidence.medium
          : Confidence.low;
    } else {
      growthAssumption = ForecastGrowthAssumption(
        rate: fallbackGrowthRate,
        basis: ForecastGrowthBasis.defaultRate,
        explanation:
            'Estimated from the documented default growth rate '
            '(${fallbackGrowthRate.format(withSign: true)} p.a.) because '
            'fewer than three complete growth years are available.',
      );
      confidence = Confidence.low;
    }

    final List<DividendEvent> output = <DividendEvent>[...knownFuture];
    final Set<DividendEvent> usedKnown = <DividendEvent>{};
    final Duration matchTolerance = _matchTolerance(frequency);

    for (int slot = 0; slot < schedule.events.length; slot++) {
      final DividendEvent baseEvent = schedule.events[slot];
      Money basisAmount = baseEvent.amountPerShare;
      int basisYear = schedule.year;

      for (final DividendEvent historical in reported) {
        final DateTime? date = schedule.matchingDateOf(historical);
        if (date == null ||
            date.year <= basisYear ||
            !_calendarDay(date).isBefore(start)) {
          continue;
        }
        final DateTime candidate = schedule.dateFor(slot, date.year);
        if (_calendarDistance(date, candidate) <= matchTolerance) {
          basisAmount = historical.amountPerShare;
          basisYear = date.year;
        }
      }

      for (int year = start.year; year <= end.year; year++) {
        final DateTime candidate = schedule.dateFor(slot, year);
        if (candidate.isBefore(start) || !candidate.isBefore(end)) {
          continue;
        }
        final DividendEvent? known = _nearestKnown(
          knownFuture,
          usedKnown,
          candidate,
          schedule,
          matchTolerance,
        );
        if (known != null) {
          usedKnown.add(known);
          basisAmount = known.amountPerShare;
          basisYear = year;
          continue;
        }
        if (!basisAmount.isPositive) {
          continue;
        }
        final Money estimatedAmount = Money(
          _grow(basisAmount.amount, growthAssumption.rate, year - basisYear),
          currency,
        );
        output.add(
          DividendEvent(
            instrumentId: instrumentId,
            amountPerShare: estimatedAmount,
            status: DividendStatus.historicallyEstimated,
            exDate: schedule.usesExDate
                ? candidate
                : schedule.exDateFor(candidate),
            paymentDate: schedule.usesExDate
                ? schedule.paymentDateFor(candidate)
                : candidate,
            frequency: frequency,
            provenance: Provenance(
              source: forecastSource,
              fetchedAt: asOf,
              confidence: confidence,
              reportedCurrency: currency,
            ),
          ),
        );
      }
    }

    output.sort(
      (DividendEvent left, DividendEvent right) =>
          _primaryDate(left)!.compareTo(_primaryDate(right)!),
    );
    return DividendForecast(
      instrumentId: instrumentId,
      currency: currency,
      status: DividendForecastStatus.available,
      frequency: frequency,
      events: List<DividendEvent>.unmodifiable(output),
      asOf: start,
      horizonEnd: end,
      growthAssumption: growthAssumption,
      confidence: confidence,
      explanation:
          '${frequency.name} seasonality from $completeScheduleYears complete '
          '${completeScheduleYears == 1 ? 'year' : 'years'}. '
          '${growthAssumption.explanation}',
    );
  }

  static DividendForecast _unavailable({
    required String instrumentId,
    required Currency currency,
    required DividendForecastStatus status,
    required DividendFrequency frequency,
    required List<DividendEvent> knownFuture,
    required DateTime start,
    required DateTime end,
    required String explanation,
  }) {
    final List<DividendEvent> sorted = List<DividendEvent>.of(knownFuture)
      ..sort(
        (DividendEvent left, DividendEvent right) =>
            _primaryDate(left)!.compareTo(_primaryDate(right)!),
      );
    return DividendForecast(
      instrumentId: instrumentId,
      currency: currency,
      status: status,
      frequency: frequency,
      events: List<DividendEvent>.unmodifiable(sorted),
      asOf: start,
      horizonEnd: end,
      explanation: explanation,
    );
  }

  static DividendFrequency _inferFrequency(
    List<DividendEvent> events,
    int currentYear,
  ) {
    final Map<DividendFrequency, int> explicit = <DividendFrequency, int>{};
    bool explicitlyIrregular = false;
    for (final DividendEvent event in events) {
      if (event.frequency.paymentsPerYear != null) {
        explicit[event.frequency] = (explicit[event.frequency] ?? 0) + 1;
      } else if (event.frequency == DividendFrequency.irregular) {
        explicitlyIrregular = true;
      }
    }
    if (explicit.isNotEmpty) {
      final List<MapEntry<DividendFrequency, int>> ranked =
          explicit.entries.toList()..sort(
            (
              MapEntry<DividendFrequency, int> left,
              MapEntry<DividendFrequency, int> right,
            ) => right.value.compareTo(left.value),
          );
      if (ranked.length > 1 && ranked[0].value == ranked[1].value) {
        return DividendFrequency.irregular;
      }
      return ranked.first.key;
    }
    if (explicitlyIrregular) {
      return DividendFrequency.irregular;
    }

    final Map<int, int> countsByYear = <int, int>{};
    for (final DividendEvent event in events) {
      final DateTime? date = _primaryDate(event);
      if (date != null && date.year < currentYear) {
        countsByYear[date.year] = (countsByYear[date.year] ?? 0) + 1;
      }
    }
    if (countsByYear.isEmpty) {
      return DividendFrequency.unknown;
    }
    final Map<int, int> occurrence = <int, int>{};
    for (final int count in countsByYear.values) {
      occurrence[count] = (occurrence[count] ?? 0) + 1;
    }
    final List<MapEntry<int, int>> ranked = occurrence.entries.toList()
      ..sort((MapEntry<int, int> left, MapEntry<int, int> right) {
        final int byOccurrence = right.value.compareTo(left.value);
        return byOccurrence != 0 ? byOccurrence : right.key.compareTo(left.key);
      });
    return DividendFrequency.fromPaymentsPerYear(ranked.first.key);
  }

  static _SeasonalSchedule? _findSchedule(
    List<DividendEvent> events, {
    required int beforeYear,
    required int expectedPayments,
  }) {
    // Cash-arrival dates drive income forecasts. When both dates exist, keep
    // the observed offset so generated events still expose their ex-date.
    for (final bool usesExDate in <bool>[false, true]) {
      final Map<int, List<DividendEvent>> byYear = <int, List<DividendEvent>>{};
      for (final DividendEvent event in events) {
        final DateTime? date = usesExDate ? event.exDate : event.paymentDate;
        if (date != null && date.year < beforeYear) {
          byYear.putIfAbsent(date.year, () => <DividendEvent>[]).add(event);
        }
      }
      final List<int> years = byYear.keys.toList()..sort();
      for (final int year in years.reversed) {
        final List<DividendEvent> candidates = byYear[year]!
          ..sort(
            (DividendEvent left, DividendEvent right) =>
                (usesExDate ? left.exDate! : left.paymentDate!).compareTo(
                  usesExDate ? right.exDate! : right.paymentDate!,
                ),
          );
        if (candidates.length == expectedPayments) {
          final List<int> offsets =
              candidates
                  .where(
                    (DividendEvent event) =>
                        event.exDate != null && event.paymentDate != null,
                  )
                  .map(
                    (DividendEvent event) =>
                        event.paymentDate!.difference(event.exDate!).inDays,
                  )
                  .toList()
                ..sort();
          return _SeasonalSchedule(
            year: year,
            events: List<DividendEvent>.unmodifiable(candidates),
            usesExDate: usesExDate,
            paymentOffsetDays: offsets.isEmpty
                ? null
                : offsets[offsets.length ~/ 2],
          );
        }
      }
    }
    return null;
  }

  static int _completeScheduleYears(
    List<DividendEvent> events,
    _SeasonalSchedule schedule, {
    required int beforeYear,
  }) {
    final Map<int, List<DividendEvent>> byYear = <int, List<DividendEvent>>{};
    for (final DividendEvent event in events) {
      final DateTime? date = schedule.dateOf(event);
      if (date != null && date.year < beforeYear) {
        byYear.putIfAbsent(date.year, () => <DividendEvent>[]).add(event);
      }
    }
    final Duration tolerance = switch (schedule.events.length) {
      12 => const Duration(days: 10),
      4 => const Duration(days: 45),
      2 => const Duration(days: 60),
      1 => const Duration(days: 90),
      _ => Duration.zero,
    };
    int complete = 0;
    for (final MapEntry<int, List<DividendEvent>> entry in byYear.entries) {
      if (entry.value.length != schedule.events.length) {
        continue;
      }
      final Set<DividendEvent> used = <DividendEvent>{};
      bool matches = true;
      for (int slot = 0; slot < schedule.events.length; slot++) {
        final DateTime candidate = schedule.dateFor(slot, entry.key);
        final DividendEvent? match = entry.value
            .where((DividendEvent event) => !used.contains(event))
            .where(
              (DividendEvent event) =>
                  _calendarDistance(schedule.dateOf(event)!, candidate) <=
                  tolerance,
            )
            .firstOrNull;
        if (match == null) {
          matches = false;
          break;
        }
        used.add(match);
      }
      if (matches) {
        complete++;
      }
    }
    return complete;
  }

  static DividendCagr? _longestCagr(Map<int, DividendCagr> cagrs) {
    for (final int period
        in DividendGrowthCalculator.standardPeriods.reversed) {
      final DividendCagr? cagr = cagrs[period];
      if (cagr != null) {
        return cagr;
      }
    }
    return null;
  }

  static DividendEvent? _nearestKnown(
    List<DividendEvent> events,
    Set<DividendEvent> used,
    DateTime candidate,
    _SeasonalSchedule schedule,
    Duration tolerance,
  ) {
    DividendEvent? nearest;
    Duration? nearestDistance;
    for (final DividendEvent event in events) {
      if (used.contains(event)) {
        continue;
      }
      final DateTime? date = schedule.matchingDateOf(event);
      if (date == null || date.year != candidate.year) {
        continue;
      }
      final Duration distance = _calendarDistance(date, candidate);
      if (distance <= tolerance &&
          (nearestDistance == null || distance < nearestDistance)) {
        nearest = event;
        nearestDistance = distance;
      }
    }
    return nearest;
  }

  static Duration _matchTolerance(DividendFrequency frequency) =>
      switch (frequency) {
        DividendFrequency.monthly => const Duration(days: 10),
        DividendFrequency.quarterly => const Duration(days: 45),
        DividendFrequency.semiAnnual => const Duration(days: 60),
        DividendFrequency.annual => const Duration(days: 90),
        DividendFrequency.irregular ||
        DividendFrequency.unknown => Duration.zero,
      };

  static Decimal _grow(Decimal amount, Percentage rate, int years) {
    Decimal result = amount;
    final Decimal factor = Decimal.one + rate.rate;
    for (int index = 0; index < years; index++) {
      result *= factor;
    }
    return result.round(scale: 6);
  }

  static DateTime? _primaryDate(DividendEvent event) =>
      event.exDate ?? event.paymentDate;

  static DateTime _calendarDay(DateTime value) =>
      DateTime.utc(value.year, value.month, value.day);

  static Duration _calendarDistance(DateTime left, DateTime right) =>
      _calendarDay(left).difference(_calendarDay(right)).abs();

  static DateTime _addMonths(DateTime value, int months) {
    final int zeroBasedMonth = value.month - 1 + months;
    final int year = value.year + zeroBasedMonth ~/ 12;
    final int month = zeroBasedMonth % 12 + 1;
    final int day = value.day.clamp(1, _daysInMonth(year, month));
    return DateTime.utc(year, month, day);
  }

  static int _daysInMonth(int year, int month) =>
      DateTime.utc(year, month + 1).subtract(const Duration(days: 1)).day;
}

final class _SeasonalSchedule {
  const _SeasonalSchedule({
    required this.year,
    required this.events,
    required this.usesExDate,
    required this.paymentOffsetDays,
  });

  final int year;
  final List<DividendEvent> events;
  final bool usesExDate;
  final int? paymentOffsetDays;

  DateTime? dateOf(DividendEvent event) =>
      usesExDate ? event.exDate : event.paymentDate;

  DateTime? matchingDateOf(DividendEvent event) {
    final DateTime? direct = dateOf(event);
    if (direct != null) {
      return direct;
    }
    final int? offset = paymentOffsetDays;
    if (offset == null) {
      return null;
    }
    if (usesExDate && event.paymentDate != null) {
      return event.paymentDate!.subtract(Duration(days: offset));
    }
    if (!usesExDate && event.exDate != null) {
      return event.exDate!.add(Duration(days: offset));
    }
    return null;
  }

  DateTime dateFor(int slot, int targetYear) {
    final DateTime source = dateOf(events[slot])!;
    final int day = source.day.clamp(
      1,
      DividendForecastEngine._daysInMonth(targetYear, source.month),
    );
    return DateTime.utc(targetYear, source.month, day);
  }

  DateTime? paymentDateFor(DateTime exDate) => paymentOffsetDays == null
      ? null
      : exDate.add(Duration(days: paymentOffsetDays!));

  DateTime? exDateFor(DateTime paymentDate) => paymentOffsetDays == null
      ? null
      : paymentDate.subtract(Duration(days: paymentOffsetDays!));
}
